// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOtBTJtYBLfpSi2lVNAsLM3c-VK7Bh8kY',
    appId: '1:972175089727:web:9fcf9ecf1542f9ace3588a',
    messagingSenderId: '972175089727',
    projectId: 'app-loginjorge',
    authDomain: 'app-loginjorge.firebaseapp.com',
    storageBucket: 'app-loginjorge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiSHRTHnAhJAaRFRmxUEZ_AhUYszhr5B4',
    appId: '1:972175089727:android:ff3d051dc67da6c7e3588a',
    messagingSenderId: '972175089727',
    projectId: 'app-loginjorge',
    storageBucket: 'app-loginjorge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8tz9loZutdR2OYstJplqt_Vkn4cBOwf8',
    appId: '1:972175089727:ios:5731428714ca71d9e3588a',
    messagingSenderId: '972175089727',
    projectId: 'app-loginjorge',
    storageBucket: 'app-loginjorge.appspot.com',
    iosBundleId: 'com.example.appLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8tz9loZutdR2OYstJplqt_Vkn4cBOwf8',
    appId: '1:972175089727:ios:5731428714ca71d9e3588a',
    messagingSenderId: '972175089727',
    projectId: 'app-loginjorge',
    storageBucket: 'app-loginjorge.appspot.com',
    iosBundleId: 'com.example.appLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOtBTJtYBLfpSi2lVNAsLM3c-VK7Bh8kY',
    appId: '1:972175089727:web:2169239952e549ade3588a',
    messagingSenderId: '972175089727',
    projectId: 'app-loginjorge',
    authDomain: 'app-loginjorge.firebaseapp.com',
    storageBucket: 'app-loginjorge.appspot.com',
  );
}
